# conda env create -f environment.yml
name: xopt-dev
channels:
  - conda-forge
dependencies:
  - python=3.9
  - deap
  - numpy
  - pydantic
  - pyyaml
  - pytorch
  - botorch
  - gpytorch
  - pandas
  - ipywidgets
  - tqdm
# parallel
  - mpi4py
  - dask
# Developer
  - pytest
  - jupyterlab>=3
  - matplotlib
  - pygments
  - mkdocs
  - mkdocstrings
  - mkdocs-material
  - mkdocs-jupyter
  - pre-commit
  - flake8
  - pip:
    - ufmt


#  - pip:
#    - git+git://github.com/some/repo
