# conda env create -f environment.yml
name: xopt-dev
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - deap
  - numpy
  - pydantic>=2.3
  - pyyaml
  - botorch
  - scipy>=1.10.1
  - pandas
  - ipywidgets
  - tqdm
  - orjson
  - matplotlib
# parallel
  - mpi4py
  - dask
# Developer
  - ffmpeg
  - pytest
  - pytest-cov
  - jupyterlab>=3
  - jupyterlab-lsp
  - python-lsp-server
  - pygments
  - mkdocs
  - mkdocstrings
  - mkdocs-material
  - mkdocs-jupyter
  - mkdocstrings-python
  - ruff
  - typing-extensions
