# conda env create -f environment.yml
name: xopt-dev
channels:
  - conda-forge
dependencies:
  - python=3.9
  - deap
  - numpy
  - pydantic>=1.10.0
  - pyyaml
  - botorch>=0.8.2
  - pandas
  - ipywidgets
  - tqdm
  - orjson
# parallel
  - mpi4py
  - dask
# Developer
  - pytest
  - pytest-cov
  - jupyterlab>=3
  - matplotlib
  - pygments
  - mkdocs
  - mkdocstrings
  - mkdocs-material
  - mkdocs-jupyter
  - mkdocstrings-python
  - pre-commit
  - flake8
  - pip
  - pip:
    - ufmt
#  - pip:
#    - git+git://github.com/some/repo
