name: Lint
on:
  pull_request:
  workflow_dispatch:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.12

      - name: Install dependencies
        run: uv sync --extra dev --index pytorch-cpu

      - name: Install pre-commit
        run: uv pip install pre-commit

      - name: List Python package versions
        run: uv pip list

      - name: Run notebook clearing check first (no diff)
        env:
          RUFF_OUTPUT_FORMAT: github
        run: |
          uv run pre-commit run jupyter-notebook-clear-output --all-files

      - name: Switch to a temporary branch
        run: |
          git checkout -b _ci_branch_

      - name: Run pre-commit on all files
        env:
          RUFF_OUTPUT_FORMAT: github
        run: |
          uv run pre-commit run \
            --show-diff-on-failure \
            --color=always \
            --all-files
